ALPHA_OBJECTS= \
    $(_OBJ_DIR)\alpha\comstd.res \
    $(_OBJ_DIR)\alpha\comstd.obj

PASS0_ALPHA_OBJECTS=

ALPHA64_OBJECTS= \
    $(_OBJ_DIR)\alpha64\comstd.res \
    $(_OBJ_DIR)\alpha64\comstd.obj

PASS0_ALPHA64_OBJECTS=

386_OBJECTS= \
    $(_OBJ_DIR)\i386\comstd.res \
    $(_OBJ_DIR)\i386\comstd.obj

PASS0_386_OBJECTS=

IA64_OBJECTS= \
    $(_OBJ_DIR)\ia64\comstd.res \
    $(_OBJ_DIR)\ia64\comstd.obj

PASS0_IA64_OBJECTS=

