ALPHA_OBJECTS= \
    $(_OBJ_DIR)\alpha\htrn_jis.res \
    $(_OBJ_DIR)\alpha\htrn_jis.obj

PASS0_ALPHA_OBJECTS=

ALPHA64_OBJECTS= \
    $(_OBJ_DIR)\alpha64\htrn_jis.res \
    $(_OBJ_DIR)\alpha64\htrn_jis.obj

PASS0_ALPHA64_OBJECTS=

386_OBJECTS= \
    $(_OBJ_DIR)\i386\htrn_jis.res \
    $(_OBJ_DIR)\i386\htrn_jis.obj

PASS0_386_OBJECTS=

IA64_OBJECTS= \
    $(_OBJ_DIR)\ia64\htrn_jis.res \
    $(_OBJ_DIR)\ia64\htrn_jis.obj

PASS0_IA64_OBJECTS=

