ALPHA_OBJECTS= \
    $(_OBJ_DIR)\alpha\tprov1.res \
    $(_OBJ_DIR)\alpha\testprov.obj

PASS0_ALPHA_OBJECTS=

ALPHA64_OBJECTS= \
    $(_OBJ_DIR)\alpha64\tprov1.res \
    $(_OBJ_DIR)\alpha64\testprov.obj

PASS0_ALPHA64_OBJECTS=

386_OBJECTS= \
    $(_OBJ_DIR)\i386\tprov1.res \
    $(_OBJ_DIR)\i386\testprov.obj

PASS0_386_OBJECTS=

IA64_OBJECTS= \
    $(_OBJ_DIR)\ia64\tprov1.res \
    $(_OBJ_DIR)\ia64\testprov.obj

PASS0_IA64_OBJECTS=

