ALPHA_OBJECTS= \
    $(_OBJ_DIR)\alpha\chktrust.res \
    $(_OBJ_DIR)\alpha\chktrust.obj

PASS0_ALPHA_OBJECTS=

ALPHA64_OBJECTS= \
    $(_OBJ_DIR)\alpha64\chktrust.res \
    $(_OBJ_DIR)\alpha64\chktrust.obj

PASS0_ALPHA64_OBJECTS=

386_OBJECTS= \
    $(_OBJ_DIR)\i386\chktrust.res \
    $(_OBJ_DIR)\i386\chktrust.obj

PASS0_386_OBJECTS=

IA64_OBJECTS= \
    $(_OBJ_DIR)\ia64\chktrust.res \
    $(_OBJ_DIR)\ia64\chktrust.obj

PASS0_IA64_OBJECTS=

