ALPHA_OBJECTS= \
    $(_OBJ_DIR)\alpha\snmp.res \
    $(_OBJ_DIR)\alpha\args.obj \
    $(_OBJ_DIR)\alpha\contexts.obj \
    $(_OBJ_DIR)\alpha\globals.obj \
    $(_OBJ_DIR)\alpha\mem.obj \
    $(_OBJ_DIR)\alpha\network.obj \
    $(_OBJ_DIR)\alpha\regions.obj \
    $(_OBJ_DIR)\alpha\registry.obj \
    $(_OBJ_DIR)\alpha\service.obj \
    $(_OBJ_DIR)\alpha\snmpevts.obj \
    $(_OBJ_DIR)\alpha\snmpmgrs.obj \
    $(_OBJ_DIR)\alpha\snmppdus.obj \
    $(_OBJ_DIR)\alpha\snmpthrd.obj \
    $(_OBJ_DIR)\alpha\regthrd.obj \
    $(_OBJ_DIR)\alpha\startup.obj \
    $(_OBJ_DIR)\alpha\subagnts.obj \
    $(_OBJ_DIR)\alpha\trapmgrs.obj \
    $(_OBJ_DIR)\alpha\trapthrd.obj \
    $(_OBJ_DIR)\alpha\query.obj \
    $(_OBJ_DIR)\alpha\varbinds.obj \
    $(_OBJ_DIR)\alpha\snmpmgmt.obj

PASS0_ALPHA_OBJECTS=

ALPHA64_OBJECTS= \
    $(_OBJ_DIR)\alpha64\snmp.res \
    $(_OBJ_DIR)\alpha64\args.obj \
    $(_OBJ_DIR)\alpha64\contexts.obj \
    $(_OBJ_DIR)\alpha64\globals.obj \
    $(_OBJ_DIR)\alpha64\mem.obj \
    $(_OBJ_DIR)\alpha64\network.obj \
    $(_OBJ_DIR)\alpha64\regions.obj \
    $(_OBJ_DIR)\alpha64\registry.obj \
    $(_OBJ_DIR)\alpha64\service.obj \
    $(_OBJ_DIR)\alpha64\snmpevts.obj \
    $(_OBJ_DIR)\alpha64\snmpmgrs.obj \
    $(_OBJ_DIR)\alpha64\snmppdus.obj \
    $(_OBJ_DIR)\alpha64\snmpthrd.obj \
    $(_OBJ_DIR)\alpha64\regthrd.obj \
    $(_OBJ_DIR)\alpha64\startup.obj \
    $(_OBJ_DIR)\alpha64\subagnts.obj \
    $(_OBJ_DIR)\alpha64\trapmgrs.obj \
    $(_OBJ_DIR)\alpha64\trapthrd.obj \
    $(_OBJ_DIR)\alpha64\query.obj \
    $(_OBJ_DIR)\alpha64\varbinds.obj \
    $(_OBJ_DIR)\alpha64\snmpmgmt.obj

PASS0_ALPHA64_OBJECTS=

386_OBJECTS= \
    $(_OBJ_DIR)\i386\snmp.res \
    $(_OBJ_DIR)\i386\args.obj \
    $(_OBJ_DIR)\i386\contexts.obj \
    $(_OBJ_DIR)\i386\globals.obj \
    $(_OBJ_DIR)\i386\mem.obj \
    $(_OBJ_DIR)\i386\network.obj \
    $(_OBJ_DIR)\i386\regions.obj \
    $(_OBJ_DIR)\i386\registry.obj \
    $(_OBJ_DIR)\i386\service.obj \
    $(_OBJ_DIR)\i386\snmpevts.obj \
    $(_OBJ_DIR)\i386\snmpmgrs.obj \
    $(_OBJ_DIR)\i386\snmppdus.obj \
    $(_OBJ_DIR)\i386\snmpthrd.obj \
    $(_OBJ_DIR)\i386\regthrd.obj \
    $(_OBJ_DIR)\i386\startup.obj \
    $(_OBJ_DIR)\i386\subagnts.obj \
    $(_OBJ_DIR)\i386\trapmgrs.obj \
    $(_OBJ_DIR)\i386\trapthrd.obj \
    $(_OBJ_DIR)\i386\query.obj \
    $(_OBJ_DIR)\i386\varbinds.obj \
    $(_OBJ_DIR)\i386\snmpmgmt.obj

PASS0_386_OBJECTS=

IA64_OBJECTS= \
    $(_OBJ_DIR)\ia64\snmp.res \
    $(_OBJ_DIR)\ia64\args.obj \
    $(_OBJ_DIR)\ia64\contexts.obj \
    $(_OBJ_DIR)\ia64\globals.obj \
    $(_OBJ_DIR)\ia64\mem.obj \
    $(_OBJ_DIR)\ia64\network.obj \
    $(_OBJ_DIR)\ia64\regions.obj \
    $(_OBJ_DIR)\ia64\registry.obj \
    $(_OBJ_DIR)\ia64\service.obj \
    $(_OBJ_DIR)\ia64\snmpevts.obj \
    $(_OBJ_DIR)\ia64\snmpmgrs.obj \
    $(_OBJ_DIR)\ia64\snmppdus.obj \
    $(_OBJ_DIR)\ia64\snmpthrd.obj \
    $(_OBJ_DIR)\ia64\regthrd.obj \
    $(_OBJ_DIR)\ia64\startup.obj \
    $(_OBJ_DIR)\ia64\subagnts.obj \
    $(_OBJ_DIR)\ia64\trapmgrs.obj \
    $(_OBJ_DIR)\ia64\trapthrd.obj \
    $(_OBJ_DIR)\ia64\query.obj \
    $(_OBJ_DIR)\ia64\varbinds.obj \
    $(_OBJ_DIR)\ia64\snmpmgmt.obj

PASS0_IA64_OBJECTS=

