ALPHA_OBJECTS= \
    $(_OBJ_DIR)\alpha\fixlinks.res \
    $(_OBJ_DIR)\alpha\fixlinks.obj

PASS0_ALPHA_OBJECTS=

ALPHA64_OBJECTS= \
    $(_OBJ_DIR)\alpha64\fixlinks.res \
    $(_OBJ_DIR)\alpha64\fixlinks.obj

PASS0_ALPHA64_OBJECTS=

386_OBJECTS= \
    $(_OBJ_DIR)\i386\fixlinks.res \
    $(_OBJ_DIR)\i386\fixlinks.obj

PASS0_386_OBJECTS=

IA64_OBJECTS= \
    $(_OBJ_DIR)\ia64\fixlinks.res \
    $(_OBJ_DIR)\ia64\fixlinks.obj

PASS0_IA64_OBJECTS=

