ALPHA_OBJECTS= \
    $(_OBJ_DIR)\alpha\makecat.res \
    $(_OBJ_DIR)\alpha\makecat.obj

PASS0_ALPHA_OBJECTS=

ALPHA64_OBJECTS= \
    $(_OBJ_DIR)\alpha64\makecat.res \
    $(_OBJ_DIR)\alpha64\makecat.obj

PASS0_ALPHA64_OBJECTS=

386_OBJECTS= \
    $(_OBJ_DIR)\i386\makecat.res \
    $(_OBJ_DIR)\i386\makecat.obj

PASS0_386_OBJECTS=

IA64_OBJECTS= \
    $(_OBJ_DIR)\ia64\makecat.res \
    $(_OBJ_DIR)\ia64\makecat.obj

PASS0_IA64_OBJECTS=

