ALPHA_OBJECTS= \
    $(_OBJ_DIR)\alpha\tcatdb.res \
    $(_OBJ_DIR)\alpha\tcatdb.obj

PASS0_ALPHA_OBJECTS=

ALPHA64_OBJECTS= \
    $(_OBJ_DIR)\alpha64\tcatdb.res \
    $(_OBJ_DIR)\alpha64\tcatdb.obj

PASS0_ALPHA64_OBJECTS=

386_OBJECTS= \
    $(_OBJ_DIR)\i386\tcatdb.res \
    $(_OBJ_DIR)\i386\tcatdb.obj

PASS0_386_OBJECTS=

IA64_OBJECTS= \
    $(_OBJ_DIR)\ia64\tcatdb.res \
    $(_OBJ_DIR)\ia64\tcatdb.obj

PASS0_IA64_OBJECTS=

