ALPHA_OBJECTS= \
    $(_OBJ_DIR)\alpha\folder.res \
    $(_OBJ_DIR)\alpha\folder.obj

PASS0_ALPHA_OBJECTS=

ALPHA64_OBJECTS= \
    $(_OBJ_DIR)\alpha64\folder.res \
    $(_OBJ_DIR)\alpha64\folder.obj

PASS0_ALPHA64_OBJECTS=

386_OBJECTS= \
    $(_OBJ_DIR)\i386\folder.res \
    $(_OBJ_DIR)\i386\folder.obj

PASS0_386_OBJECTS=

IA64_OBJECTS= \
    $(_OBJ_DIR)\ia64\folder.res \
    $(_OBJ_DIR)\ia64\folder.obj

PASS0_IA64_OBJECTS=

