ALPHA_OBJECTS= \
    $(_OBJ_DIR)\alpha\snmpmib.res \
    $(_OBJ_DIR)\alpha\dllmain.obj \
    $(_OBJ_DIR)\alpha\mibentry.obj \
    $(_OBJ_DIR)\alpha\mibfuncs.obj

PASS0_ALPHA_OBJECTS=

ALPHA64_OBJECTS= \
    $(_OBJ_DIR)\alpha64\snmpmib.res \
    $(_OBJ_DIR)\alpha64\dllmain.obj \
    $(_OBJ_DIR)\alpha64\mibentry.obj \
    $(_OBJ_DIR)\alpha64\mibfuncs.obj

PASS0_ALPHA64_OBJECTS=

386_OBJECTS= \
    $(_OBJ_DIR)\i386\snmpmib.res \
    $(_OBJ_DIR)\i386\dllmain.obj \
    $(_OBJ_DIR)\i386\mibentry.obj \
    $(_OBJ_DIR)\i386\mibfuncs.obj

PASS0_386_OBJECTS=

IA64_OBJECTS= \
    $(_OBJ_DIR)\ia64\snmpmib.res \
    $(_OBJ_DIR)\ia64\dllmain.obj \
    $(_OBJ_DIR)\ia64\mibentry.obj \
    $(_OBJ_DIR)\ia64\mibfuncs.obj

PASS0_IA64_OBJECTS=

