ALPHA_OBJECTS= \
    $(_OBJ_DIR)\alpha\thumnail.obj \
    $(_OBJ_DIR)\alpha\pal.obj

PASS0_ALPHA_OBJECTS=

ALPHA64_OBJECTS= \
    $(_OBJ_DIR)\alpha64\thumnail.obj \
    $(_OBJ_DIR)\alpha64\pal.obj

PASS0_ALPHA64_OBJECTS=

386_OBJECTS= \
    $(_OBJ_DIR)\i386\thumnail.obj \
    $(_OBJ_DIR)\i386\pal.obj

PASS0_386_OBJECTS=

IA64_OBJECTS= \
    $(_OBJ_DIR)\ia64\thumnail.obj \
    $(_OBJ_DIR)\ia64\pal.obj

PASS0_IA64_OBJECTS=

