ALPHA_OBJECTS= \
    $(_OBJ_DIR)\alpha\stress.res \
    $(_OBJ_DIR)\alpha\stress.obj

PASS0_ALPHA_OBJECTS=

ALPHA64_OBJECTS= \
    $(_OBJ_DIR)\alpha64\stress.res \
    $(_OBJ_DIR)\alpha64\stress.obj

PASS0_ALPHA64_OBJECTS=

386_OBJECTS= \
    $(_OBJ_DIR)\i386\stress.res \
    $(_OBJ_DIR)\i386\stress.obj

PASS0_386_OBJECTS=

IA64_OBJECTS= \
    $(_OBJ_DIR)\ia64\stress.res \
    $(_OBJ_DIR)\ia64\stress.obj

PASS0_IA64_OBJECTS=

