ALPHA_OBJECTS= \
    $(_OBJ_DIR)\alpha\hmmapi.res \
    $(_OBJ_DIR)\alpha\hmmapi.obj

PASS0_ALPHA_OBJECTS=

ALPHA64_OBJECTS= \
    $(_OBJ_DIR)\alpha64\hmmapi.res \
    $(_OBJ_DIR)\alpha64\hmmapi.obj

PASS0_ALPHA64_OBJECTS=

386_OBJECTS= \
    $(_OBJ_DIR)\i386\hmmapi.res \
    $(_OBJ_DIR)\i386\hmmapi.obj

PASS0_386_OBJECTS=

IA64_OBJECTS= \
    $(_OBJ_DIR)\ia64\hmmapi.res \
    $(_OBJ_DIR)\ia64\hmmapi.obj

PASS0_IA64_OBJECTS=

