ALPHA_OBJECTS= \
    $(_OBJ_DIR)\alpha\unicrt.obj \
    $(_OBJ_DIR)\alpha\unifile.obj

PASS0_ALPHA_OBJECTS=

ALPHA64_OBJECTS= \
    $(_OBJ_DIR)\alpha64\unicrt.obj \
    $(_OBJ_DIR)\alpha64\unifile.obj

PASS0_ALPHA64_OBJECTS=

386_OBJECTS= \
    $(_OBJ_DIR)\i386\unicrt.obj \
    $(_OBJ_DIR)\i386\unifile.obj

PASS0_386_OBJECTS=

IA64_OBJECTS= \
    $(_OBJ_DIR)\ia64\unicrt.obj \
    $(_OBJ_DIR)\ia64\unifile.obj

PASS0_IA64_OBJECTS=

