/*++ BUILD Version: 0001    // Increment this if a change has global effects

Copyright (c) 1992  Microsoft Corporation

Module Name:

    wlevents.h

Abstract:

    Definitions for User Profiles Events

Author:

    Johannec 12-08-93

Revision History:

Notes:

    This file is generated by the MC tool from the wlevents.mc file.

--*/


#ifndef _PROFEVT_
#define _PROFEVT_


/////////////////////////////////////////////////////////////////////////
//
// Winlogon Events (1000 - 1999)
//
/////////////////////////////////////////////////////////////////////////

//
//  Values are 32 bit values layed out as follows:
//
//   3 3 2 2 2 2 2 2 2 2 2 2 1 1 1 1 1 1 1 1 1 1
//   1 0 9 8 7 6 5 4 3 2 1 0 9 8 7 6 5 4 3 2 1 0 9 8 7 6 5 4 3 2 1 0
//  +---+-+-+-----------------------+-------------------------------+
//  |Sev|C|R|     Facility          |               Code            |
//  +---+-+-+-----------------------+-------------------------------+
//
//  where
//
//      Sev - is the severity code
//
//          00 - Success
//          01 - Informational
//          10 - Warning
//          11 - Error
//
//      C - is the Customer code flag
//
//      R - is a reserved bit
//
//      Facility - is the facility code
//
//      Code - is the facility's status code
//
//
// Define the facility codes
//


//
// Define the severity codes
//
#define STATUS_SEVERITY_WARNING          0x2
#define STATUS_SEVERITY_SUCCESS          0x0
#define STATUS_SEVERITY_INFORMATIONAL    0x1
#define STATUS_SEVERITY_ERROR            0x3


//
// MessageId: EVENT_SET_HOME_DIRECTORY_FAILED
//
// MessageText:
//
//  Failed to set the user's home directory %1.
//
#define EVENT_SET_HOME_DIRECTORY_FAILED  0xC00003E8L

//
// MessageId: EVENT_AUTOCHK_DATA
//
// MessageText:
//
//  %1
//
#define EVENT_AUTOCHK_DATA               0x400003E9L

//
// MessageId: EVENT_SHELL_RESTARTED
//
// MessageText:
//
//  The shell stopped unexpectedly and %1 was restarted.
//
#define EVENT_SHELL_RESTARTED            0x400003EAL

//
// MessageId: EVENT_AE_INITIALIZATION_FAILED
//
// MessageText:
//
//  Initialization of automatic certificate enrollment has failed.  There is possible corruption
//  of system DLL's required for auto-enrollment.  (%1) %2
//
#define EVENT_AE_INITIALIZATION_FAILED   0xC00003EBL

//
// MessageId: EVENT_UAE_VERIFICATION_FAILURE
//
// MessageText:
//
//  Verification of an automatically enrolled certificate has failed. (%1) %2
//
#define EVENT_UAE_VERIFICATION_FAILURE   0xC00003ECL

//
// MessageId: EVENT_UAE_UNKNOWN_CERT_TYPE
//
// MessageText:
//
//  Unknown or unavailable cert type, %3, requested for automatic certificate enrollment.
//  This enrollment will not be performed. (%1) %2
//
#define EVENT_UAE_UNKNOWN_CERT_TYPE      0xC00003EDL

//
// MessageId: EVENT_OLD_CERT_VERIFY_RENEW_WARNING
//
// MessageText:
//
//  
//  The automatically enrolled certificate of type %1 is being renewed for the following reason(s):
//  %2
//
#define EVENT_OLD_CERT_VERIFY_RENEW_WARNING 0x400003EEL

//
// MessageId: EVENT_OLD_CERT_VERIFY_REENROLL_WARNING
//
// MessageText:
//
//  The automatically enrolled certificate of type %1 is being re-enrolled for the following reason(s):
//  %2
//
#define EVENT_OLD_CERT_VERIFY_REENROLL_WARNING 0x400003EFL

//
// MessageId: EVENT_UPDATE_ENTERPRISE_ROOT_FAILURE
//
// MessageText:
//
//  The enterprise root certificate store could not be updated.
//  (%1) %2.
//
#define EVENT_UPDATE_ENTERPRISE_ROOT_FAILURE 0xC00003F0L

//
// MessageId: EVENT_UPDATE_NTAUTH_FAILURE
//
// MessageText:
//
//  The NT Smartcard authentication certificate store could not be updated.
//  (%1) %2.
//
#define EVENT_UPDATE_NTAUTH_FAILURE      0xC00003F1L

//
// MessageId: EVENT_AE_ENROLLMENT_FAILED
//
// MessageText:
//
//  Automatic enrollment against the certification authority %4 for a certificate of type %3 has
//  failed.  (%1) %2.   Another certification authority will be tried.
//
#define EVENT_AE_ENROLLMENT_FAILED       0x800003F2L

//
// MessageId: EVENT_ENROLLED_CERT_VERIFY_WARNING
//
// MessageText:
//
//  The certificate returned from an auto-enrollment is incorrect.  Subsequent auto-enrollment cycles
//  will ignore reasons for failure.  Please contact your system administrator.  The reasons for failure are
//  listed below:
//  %2
//
#define EVENT_ENROLLED_CERT_VERIFY_WARNING 0x800003F3L

//
// MessageId: EVENT_AE_LOCAL_CYCLE_INIT_FAILED
//
// MessageText:
//
//  The automatic certificate enrollment subsystem could not access local resources needed for enrollment.  
//  Enrollment will not be performed. (%1) %2
//
#define EVENT_AE_LOCAL_CYCLE_INIT_FAILED 0xC00003F4L

//
// MessageId: EVENT_AE_NETWORK_CYCLE_INIT_FAILED
//
// MessageText:
//
//  The automatic certificate enrollment subsystem could not access network resources needed for enrollment.  
//  Enrollment will not be performed. (%1) %2
//
#define EVENT_AE_NETWORK_CYCLE_INIT_FAILED 0xC00003F5L

//
// MessageId: EVENT_AE_SECURITY_INIT_FAILED
//
// MessageText:
//
//  A security failure is preventing automatic certificate enrollment.  
//  Enrollment will not be performed. (%1) %2
//
#define EVENT_AE_SECURITY_INIT_FAILED    0xC00003F6L

// %1 - domain, %2 - user
//
// MessageId: MSG_MOVE_USER_QUESTION
//
// MessageText:
//
//  Welcome back to the %1 domain.  While you were offline, your settings were stored in a local account. Do you want to move them to your %1 account?%0
//
#define MSG_MOVE_USER_QUESTION           0xC000044CL

// %1 - error code (DWORD)
//
// MessageId: MSG_MOVE_USER_ERROR
//
// MessageText:
//
//  Your settings cannot be moved because of an error.  (Error code %1!u!)%0
//
#define MSG_MOVE_USER_ERROR              0xC000044DL

// %1 - computer name
//
// MessageId: MSG_MY_COMPUTER
//
// MessageText:
//
//  %1 (this computer)%0
//
#define MSG_MY_COMPUTER                  0xC000044EL

// %1 - user name
//
// MessageId: MSG_LOCAL_BAD_PASSWORD
//
// MessageText:
//
//  The system could not validate %1. Check your account name, and type your password again. Letters in passwords must be typed using the correct case. Make sure that Caps Lock is not accidentially on.%0
//
#define MSG_LOCAL_BAD_PASSWORD           0xC000044FL

// %1 = user name, %2 - domain name
//
// MessageId: MSG_DOMAIN_BAD_PASSWORD
//
// MessageText:
//
//  The system could not validate %1 on %2. Check your account name, and type your password again. Letters in passwords must be typed using the correct case. Make sure that Caps Lock is not accidentially on.%0
//
#define MSG_DOMAIN_BAD_PASSWORD          0xC0000450L

// %1 - error code (DWORD)
//
// MessageId: MSG_NOT_ADMINISTRATOR
//
// MessageText:
//
//  The user account you just entered does not have the authority to move settings. Please try another account, such as Administrator.%0
//
#define MSG_NOT_ADMINISTRATOR            0xC0000451L

 //
 // Autoenrollment test events
 //
//
// MessageId: AE_TEST_EXTENSION_EKU
//
// MessageText:
//
//  The certificate does not fulfill the intended usage requirements specified by the certificate template:
//  Certificate: %1
//  Certificate Template: %2
//  
//
#define AE_TEST_EXTENSION_EKU            0x800004B0L

//
// MessageId: AE_TEST_EXTENSION_KU
//
// MessageText:
//
//  The certificate does not fulfill the key usage requirements specified by the certificate template:
//  Certificate: %1
//  Certificate Template: %2
//  
//
#define AE_TEST_EXTENSION_KU             0x800004B1L

//
// MessageId: AE_TEST_EXTENSION_BC
//
// MessageText:
//
//  The certificate does not fulfill the basic constraints requirements specified by the certificate template:
//  Certificate: %1
//  Certificate Template: %2
//  
//
#define AE_TEST_EXTENSION_BC             0x800004B2L

//
// MessageId: AE_TEST_EXTENSION_TEMPLATE
//
// MessageText:
//
//  The certificate does not contain the template name specified by the certificate template:\n
//  Certificate: %1\n
//  Certificate Template: %2
//  
//
#define AE_TEST_EXTENSION_TEMPLATE       0x800004B3L

//
// MessageId: AE_TEST_NAME_UPN
//
// MessageText:
//
//  The certificate does not contain the any of the principal names specified for this user:
//  Principal Name(s): %1
//  
//
#define AE_TEST_NAME_UPN                 0x800004B4L

//
// MessageId: AE_TEST_NAME_SUBJECT_EMAIL
//
// MessageText:
//
//  The subject name of this certificate does not contain the e-mail name for this user:
//  User e-mail name(s): %1
//  
//
#define AE_TEST_NAME_SUBJECT_EMAIL       0x800004B5L

//
// MessageId: AE_TEST_NAME_ALT_SUBJECT_EMAIL
//
// MessageText:
//
//  The alternate subject name of this certificate does not contain the e-mail name for this user:
//  User e-mail name(s): %1
//  
//
#define AE_TEST_NAME_ALT_SUBJECT_EMAIL   0x800004B6L

//
// MessageId: AE_TEST_NAME_BOTH_SUBJECT_EMAIL
//
// MessageText:
//
//  This certificate does not contain the e-mail name for this user:
//  User e-mail name(s): %1
//  
//
#define AE_TEST_NAME_BOTH_SUBJECT_EMAIL  0x800004B7L

//
// MessageId: AE_TEST_NAME_SUBJECT_DNS
//
// MessageText:
//
//  The certificate does not contain the DNS name of the machine:
//  DNS Name(s): %1
//  
//
#define AE_TEST_NAME_SUBJECT_DNS         0x800004B8L

//
// MessageId: AE_TEST_NAME_DIRECTORY_NAME
//
// MessageText:
//
//  This certificate does not contain the Directory Name of the user or machine:
//  Directory Name(s): %1
//  
//
#define AE_TEST_NAME_DIRECTORY_NAME      0x800004B9L

//
// MessageId: AE_TEST_NAME_NO_OBJID
//
// MessageText:
//
//  This certificate does not contain the Active Directory object identifier of the user or machine.
//  
//
#define AE_TEST_NAME_NO_OBJID            0x800004BAL

//
// MessageId: AE_TEST_NAME_OBJID
//
// MessageText:
//
//  This certificate contains an Active Directory object identifier, but should not.
//  
//
#define AE_TEST_NAME_OBJID               0x800004BBL

//
// MessageId: AE_TEST_CHAIN_FAIL
//
// MessageText:
//
//  The certificate is no longer trusted for the following reason (0x%1!lx!) %2.
//  
//
#define AE_TEST_CHAIN_FAIL               0x800004BCL

//
// MessageId: AE_TEST_ISSUER_FAIL
//
// MessageText:
//
//  The certificate's issuer is no longer allowed by the autoenrollment object.
//  
//
#define AE_TEST_ISSUER_FAIL              0x800004BDL

//
// MessageId: AT_TEST_PENDING_EXPIRATION
//
// MessageText:
//
//  The certificate will expire soon.
//  
//
#define AT_TEST_PENDING_EXPIRATION       0x800004BEL

//
// MessageId: AT_TEST_SUBJECT_NAME
//
// MessageText:
//
//  Subject Name:%1
//  
//
#define AT_TEST_SUBJECT_NAME             0x400004BFL

//
// MessageId: AT_TEST_ALT_SUBJECT_NAME
//
// MessageText:
//
//  Alternate Subject Name:%1
//  
//
#define AT_TEST_ALT_SUBJECT_NAME         0x400004C0L


#endif // _PROFEVT_

