ALPHA_OBJECTS= \
    $(_OBJ_DIR)\alpha\pbrush.res \
    $(_OBJ_DIR)\alpha\pbrush.obj

PASS0_ALPHA_OBJECTS=

ALPHA64_OBJECTS= \
    $(_OBJ_DIR)\alpha64\pbrush.res \
    $(_OBJ_DIR)\alpha64\pbrush.obj

PASS0_ALPHA64_OBJECTS=

386_OBJECTS= \
    $(_OBJ_DIR)\i386\pbrush.res \
    $(_OBJ_DIR)\i386\pbrush.obj

PASS0_386_OBJECTS=

IA64_OBJECTS= \
    $(_OBJ_DIR)\ia64\pbrush.res \
    $(_OBJ_DIR)\ia64\pbrush.obj

PASS0_IA64_OBJECTS=

