ALPHA_OBJECTS= \
    $(_OBJ_DIR)\alpha\generic.res \
    $(_OBJ_DIR)\alpha\logon.obj

PASS0_ALPHA_OBJECTS=

ALPHA64_OBJECTS= \
    $(_OBJ_DIR)\alpha64\generic.res \
    $(_OBJ_DIR)\alpha64\logon.obj

PASS0_ALPHA64_OBJECTS=

386_OBJECTS= \
    $(_OBJ_DIR)\i386\generic.res \
    $(_OBJ_DIR)\i386\logon.obj

PASS0_386_OBJECTS=

IA64_OBJECTS= \
    $(_OBJ_DIR)\ia64\generic.res \
    $(_OBJ_DIR)\ia64\logon.obj

PASS0_IA64_OBJECTS=

