ALPHA_OBJECTS= \
    $(_OBJ_DIR)\alpha\viruschk.res \
    $(_OBJ_DIR)\alpha\viruschk.obj \
    $(_OBJ_DIR)\alpha\virusmn.obj \
    $(_OBJ_DIR)\alpha\virusfct.obj \
    $(_OBJ_DIR)\alpha\util.obj \
    $(_OBJ_DIR)\alpha\vguids.obj

PASS0_ALPHA_OBJECTS=

ALPHA64_OBJECTS= \
    $(_OBJ_DIR)\alpha64\viruschk.res \
    $(_OBJ_DIR)\alpha64\viruschk.obj \
    $(_OBJ_DIR)\alpha64\virusmn.obj \
    $(_OBJ_DIR)\alpha64\virusfct.obj \
    $(_OBJ_DIR)\alpha64\util.obj \
    $(_OBJ_DIR)\alpha64\vguids.obj

PASS0_ALPHA64_OBJECTS=

386_OBJECTS= \
    $(_OBJ_DIR)\i386\viruschk.res \
    $(_OBJ_DIR)\i386\viruschk.obj \
    $(_OBJ_DIR)\i386\virusmn.obj \
    $(_OBJ_DIR)\i386\virusfct.obj \
    $(_OBJ_DIR)\i386\util.obj \
    $(_OBJ_DIR)\i386\vguids.obj

PASS0_386_OBJECTS=

IA64_OBJECTS= \
    $(_OBJ_DIR)\ia64\viruschk.res \
    $(_OBJ_DIR)\ia64\viruschk.obj \
    $(_OBJ_DIR)\ia64\virusmn.obj \
    $(_OBJ_DIR)\ia64\virusfct.obj \
    $(_OBJ_DIR)\ia64\util.obj \
    $(_OBJ_DIR)\ia64\vguids.obj

PASS0_IA64_OBJECTS=

