ALPHA_OBJECTS= \
    $(_OBJ_DIR)\alpha\encode.obj \
    $(_OBJ_DIR)\alpha\unicode.obj

PASS0_ALPHA_OBJECTS=

ALPHA64_OBJECTS= \
    $(_OBJ_DIR)\alpha64\encode.obj \
    $(_OBJ_DIR)\alpha64\unicode.obj

PASS0_ALPHA64_OBJECTS=

386_OBJECTS= \
    $(_OBJ_DIR)\i386\encode.obj \
    $(_OBJ_DIR)\i386\unicode.obj

PASS0_386_OBJECTS=

IA64_OBJECTS= \
    $(_OBJ_DIR)\ia64\encode.obj \
    $(_OBJ_DIR)\ia64\unicode.obj

PASS0_IA64_OBJECTS=

