ALPHA_OBJECTS= \
    $(_OBJ_DIR)\alpha\c_eucdb.res \
    $(_OBJ_DIR)\alpha\c_eucdb.obj

PASS0_ALPHA_OBJECTS=

ALPHA64_OBJECTS= \
    $(_OBJ_DIR)\alpha64\c_eucdb.res \
    $(_OBJ_DIR)\alpha64\c_eucdb.obj

PASS0_ALPHA64_OBJECTS=

386_OBJECTS= \
    $(_OBJ_DIR)\i386\c_eucdb.res \
    $(_OBJ_DIR)\i386\c_eucdb.obj

PASS0_386_OBJECTS=

IA64_OBJECTS= \
    $(_OBJ_DIR)\ia64\c_eucdb.res \
    $(_OBJ_DIR)\ia64\c_eucdb.obj

PASS0_IA64_OBJECTS=

