ALPHA_OBJECTS= \
    $(_OBJ_DIR)\alpha\syncapp.res \
    $(_OBJ_DIR)\alpha\syncapp.obj

PASS0_ALPHA_OBJECTS=

ALPHA64_OBJECTS= \
    $(_OBJ_DIR)\alpha64\syncapp.res \
    $(_OBJ_DIR)\alpha64\syncapp.obj

PASS0_ALPHA64_OBJECTS=

386_OBJECTS= \
    $(_OBJ_DIR)\i386\syncapp.res \
    $(_OBJ_DIR)\i386\syncapp.obj

PASS0_386_OBJECTS=

IA64_OBJECTS= \
    $(_OBJ_DIR)\ia64\syncapp.res \
    $(_OBJ_DIR)\ia64\syncapp.obj

PASS0_IA64_OBJECTS=

