ALPHA_OBJECTS= \
    $(_OBJ_DIR)\alpha\tcbfile.res \
    $(_OBJ_DIR)\alpha\tcbfile.obj

PASS0_ALPHA_OBJECTS=

ALPHA64_OBJECTS= \
    $(_OBJ_DIR)\alpha64\tcbfile.res \
    $(_OBJ_DIR)\alpha64\tcbfile.obj

PASS0_ALPHA64_OBJECTS=

386_OBJECTS= \
    $(_OBJ_DIR)\i386\tcbfile.res \
    $(_OBJ_DIR)\i386\tcbfile.obj

PASS0_386_OBJECTS=

IA64_OBJECTS= \
    $(_OBJ_DIR)\ia64\tcbfile.res \
    $(_OBJ_DIR)\ia64\tcbfile.obj

PASS0_IA64_OBJECTS=

