ALPHA_OBJECTS= \
    $(_OBJ_DIR)\alpha\calchash.res \
    $(_OBJ_DIR)\alpha\calchash.obj

PASS0_ALPHA_OBJECTS=

ALPHA64_OBJECTS= \
    $(_OBJ_DIR)\alpha64\calchash.res \
    $(_OBJ_DIR)\alpha64\calchash.obj

PASS0_ALPHA64_OBJECTS=

386_OBJECTS= \
    $(_OBJ_DIR)\i386\calchash.res \
    $(_OBJ_DIR)\i386\calchash.obj

PASS0_386_OBJECTS=

IA64_OBJECTS= \
    $(_OBJ_DIR)\ia64\calchash.res \
    $(_OBJ_DIR)\ia64\calchash.obj

PASS0_IA64_OBJECTS=

