ALPHA_OBJECTS= \
    $(_OBJ_DIR)\alpha\prsparse.res \
    $(_OBJ_DIR)\alpha\prsparse.obj

PASS0_ALPHA_OBJECTS=

ALPHA64_OBJECTS= \
    $(_OBJ_DIR)\alpha64\prsparse.res \
    $(_OBJ_DIR)\alpha64\prsparse.obj

PASS0_ALPHA64_OBJECTS=

386_OBJECTS= \
    $(_OBJ_DIR)\i386\prsparse.res \
    $(_OBJ_DIR)\i386\prsparse.obj

PASS0_386_OBJECTS=

IA64_OBJECTS= \
    $(_OBJ_DIR)\ia64\prsparse.res \
    $(_OBJ_DIR)\ia64\prsparse.obj

PASS0_IA64_OBJECTS=

