ALPHA_OBJECTS= \
    $(_OBJ_DIR)\alpha\view.obj \
    $(_OBJ_DIR)\alpha\adorner.obj

PASS0_ALPHA_OBJECTS=

ALPHA64_OBJECTS= \
    $(_OBJ_DIR)\alpha64\view.obj \
    $(_OBJ_DIR)\alpha64\adorner.obj

PASS0_ALPHA64_OBJECTS=

386_OBJECTS= \
    $(_OBJ_DIR)\i386\view.obj \
    $(_OBJ_DIR)\i386\adorner.obj

PASS0_386_OBJECTS=

IA64_OBJECTS= \
    $(_OBJ_DIR)\ia64\view.obj \
    $(_OBJ_DIR)\ia64\adorner.obj

PASS0_IA64_OBJECTS=

