ALPHA_OBJECTS= \
    $(_OBJ_DIR)\alpha\msidle.res \
    $(_OBJ_DIR)\alpha\msidle.obj

PASS0_ALPHA_OBJECTS=

ALPHA64_OBJECTS= \
    $(_OBJ_DIR)\alpha64\msidle.res \
    $(_OBJ_DIR)\alpha64\msidle.obj

PASS0_ALPHA64_OBJECTS=

386_OBJECTS= \
    $(_OBJ_DIR)\i386\msidle.res \
    $(_OBJ_DIR)\i386\msidle.obj

PASS0_386_OBJECTS=

IA64_OBJECTS= \
    $(_OBJ_DIR)\ia64\msidle.res \
    $(_OBJ_DIR)\ia64\msidle.obj

PASS0_IA64_OBJECTS=

