ALPHA_OBJECTS= \
    $(_OBJ_DIR)\alpha\pautoenr.res \
    $(_OBJ_DIR)\alpha\pautoenr.obj

PASS0_ALPHA_OBJECTS=

ALPHA64_OBJECTS= \
    $(_OBJ_DIR)\alpha64\pautoenr.res \
    $(_OBJ_DIR)\alpha64\pautoenr.obj

PASS0_ALPHA64_OBJECTS=

386_OBJECTS= \
    $(_OBJ_DIR)\i386\pautoenr.res \
    $(_OBJ_DIR)\i386\pautoenr.obj

PASS0_386_OBJECTS=

IA64_OBJECTS= \
    $(_OBJ_DIR)\ia64\pautoenr.res \
    $(_OBJ_DIR)\ia64\pautoenr.obj

PASS0_IA64_OBJECTS=

