ALPHA_OBJECTS= \
    $(_OBJ_DIR)\alpha\mshta.res \
    $(_OBJ_DIR)\alpha\main.obj

PASS0_ALPHA_OBJECTS=

ALPHA64_OBJECTS= \
    $(_OBJ_DIR)\alpha64\mshta.res \
    $(_OBJ_DIR)\alpha64\main.obj

PASS0_ALPHA64_OBJECTS=

386_OBJECTS= \
    $(_OBJ_DIR)\i386\mshta.res \
    $(_OBJ_DIR)\i386\main.obj

PASS0_386_OBJECTS=

IA64_OBJECTS= \
    $(_OBJ_DIR)\ia64\mshta.res \
    $(_OBJ_DIR)\ia64\main.obj

PASS0_IA64_OBJECTS=

