ALPHA_OBJECTS= \
    $(_OBJ_DIR)\alpha\stripqts.res \
    $(_OBJ_DIR)\alpha\stripqts.obj

PASS0_ALPHA_OBJECTS=

ALPHA64_OBJECTS= \
    $(_OBJ_DIR)\alpha64\stripqts.res \
    $(_OBJ_DIR)\alpha64\stripqts.obj

PASS0_ALPHA64_OBJECTS=

386_OBJECTS= \
    $(_OBJ_DIR)\i386\stripqts.res \
    $(_OBJ_DIR)\i386\stripqts.obj

PASS0_386_OBJECTS=

IA64_OBJECTS= \
    $(_OBJ_DIR)\ia64\stripqts.res \
    $(_OBJ_DIR)\ia64\stripqts.obj

PASS0_IA64_OBJECTS=

