ALPHA_OBJECTS= \
    $(_OBJ_DIR)\alpha\msswchx.res \
    $(_OBJ_DIR)\alpha\dbg.obj

PASS0_ALPHA_OBJECTS=

ALPHA64_OBJECTS= \
    $(_OBJ_DIR)\alpha64\msswchx.res \
    $(_OBJ_DIR)\alpha64\dbg.obj

PASS0_ALPHA64_OBJECTS=

386_OBJECTS= \
    $(_OBJ_DIR)\i386\msswchx.res \
    $(_OBJ_DIR)\i386\dbg.obj

PASS0_386_OBJECTS=

IA64_OBJECTS= \
    $(_OBJ_DIR)\ia64\msswchx.res \
    $(_OBJ_DIR)\ia64\dbg.obj

PASS0_IA64_OBJECTS=

