ALPHA_OBJECTS= \
    $(_OBJ_DIR)\alpha\iesetreg.res \
    $(_OBJ_DIR)\alpha\iesetreg.obj

PASS0_ALPHA_OBJECTS=

ALPHA64_OBJECTS= \
    $(_OBJ_DIR)\alpha64\iesetreg.res \
    $(_OBJ_DIR)\alpha64\iesetreg.obj

PASS0_ALPHA64_OBJECTS=

386_OBJECTS= \
    $(_OBJ_DIR)\i386\iesetreg.res \
    $(_OBJ_DIR)\i386\iesetreg.obj

PASS0_386_OBJECTS=

IA64_OBJECTS= \
    $(_OBJ_DIR)\ia64\iesetreg.res \
    $(_OBJ_DIR)\ia64\iesetreg.obj

PASS0_IA64_OBJECTS=

