ALPHA_OBJECTS= \
    $(_OBJ_DIR)\alpha\crc32.obj \
    $(_OBJ_DIR)\alpha\krnlapi.obj

PASS0_ALPHA_OBJECTS=

ALPHA64_OBJECTS= \
    $(_OBJ_DIR)\alpha64\crc32.obj \
    $(_OBJ_DIR)\alpha64\krnlapi.obj

PASS0_ALPHA64_OBJECTS=

386_OBJECTS= \
    $(_OBJ_DIR)\i386\crc32.obj \
    $(_OBJ_DIR)\i386\krnlapi.obj

PASS0_386_OBJECTS=

IA64_OBJECTS= \
    $(_OBJ_DIR)\ia64\crc32.obj \
    $(_OBJ_DIR)\ia64\krnlapi.obj

PASS0_IA64_OBJECTS=

