ALPHA_OBJECTS= \
    $(_OBJ_DIR)\alpha\narrator.res \
    $(_OBJ_DIR)\alpha\narrator.obj

PASS0_ALPHA_OBJECTS=

ALPHA64_OBJECTS= \
    $(_OBJ_DIR)\alpha64\narrator.res \
    $(_OBJ_DIR)\alpha64\narrator.obj

PASS0_ALPHA64_OBJECTS=

386_OBJECTS= \
    $(_OBJ_DIR)\i386\narrator.res \
    $(_OBJ_DIR)\i386\narrator.obj

PASS0_386_OBJECTS=

IA64_OBJECTS= \
    $(_OBJ_DIR)\ia64\narrator.res \
    $(_OBJ_DIR)\ia64\narrator.obj

PASS0_IA64_OBJECTS=

