ALPHA_OBJECTS= \
    $(_OBJ_DIR)\alpha\siteid.obj \
    $(_OBJ_DIR)\alpha\siteidpr.obj

PASS0_ALPHA_OBJECTS=

ALPHA64_OBJECTS= \
    $(_OBJ_DIR)\alpha64\siteid.obj \
    $(_OBJ_DIR)\alpha64\siteidpr.obj

PASS0_ALPHA64_OBJECTS=

386_OBJECTS= \
    $(_OBJ_DIR)\i386\siteid.obj \
    $(_OBJ_DIR)\i386\siteidpr.obj

PASS0_386_OBJECTS=

IA64_OBJECTS= \
    $(_OBJ_DIR)\ia64\siteid.obj \
    $(_OBJ_DIR)\ia64\siteidpr.obj

PASS0_IA64_OBJECTS=

