ALPHA_OBJECTS= \
    $(_OBJ_DIR)\alpha\dumpcat.res \
    $(_OBJ_DIR)\alpha\dumpcat.obj

PASS0_ALPHA_OBJECTS=

ALPHA64_OBJECTS= \
    $(_OBJ_DIR)\alpha64\dumpcat.res \
    $(_OBJ_DIR)\alpha64\dumpcat.obj

PASS0_ALPHA64_OBJECTS=

386_OBJECTS= \
    $(_OBJ_DIR)\i386\dumpcat.res \
    $(_OBJ_DIR)\i386\dumpcat.obj

PASS0_386_OBJECTS=

IA64_OBJECTS= \
    $(_OBJ_DIR)\ia64\dumpcat.res \
    $(_OBJ_DIR)\ia64\dumpcat.obj

PASS0_IA64_OBJECTS=

