ALPHA_OBJECTS= \
    $(_OBJ_DIR)\alpha\skdll.res \
    $(_OBJ_DIR)\alpha\skdll.obj

PASS0_ALPHA_OBJECTS=

ALPHA64_OBJECTS= \
    $(_OBJ_DIR)\alpha64\skdll.res \
    $(_OBJ_DIR)\alpha64\skdll.obj

PASS0_ALPHA64_OBJECTS=

386_OBJECTS= \
    $(_OBJ_DIR)\i386\skdll.res \
    $(_OBJ_DIR)\i386\skdll.obj

PASS0_386_OBJECTS=

IA64_OBJECTS= \
    $(_OBJ_DIR)\ia64\skdll.res \
    $(_OBJ_DIR)\ia64\skdll.obj

PASS0_IA64_OBJECTS=

