ALPHA_OBJECTS= \
    $(_OBJ_DIR)\alpha\msg.res \
    $(_OBJ_DIR)\alpha\dummy.obj

PASS0_ALPHA_OBJECTS=

ALPHA64_OBJECTS= \
    $(_OBJ_DIR)\alpha64\msg.res \
    $(_OBJ_DIR)\alpha64\dummy.obj

PASS0_ALPHA64_OBJECTS=

386_OBJECTS= \
    $(_OBJ_DIR)\i386\msg.res \
    $(_OBJ_DIR)\i386\dummy.obj

PASS0_386_OBJECTS=

IA64_OBJECTS= \
    $(_OBJ_DIR)\ia64\msg.res \
    $(_OBJ_DIR)\ia64\dummy.obj

PASS0_IA64_OBJECTS=

