ALPHA_OBJECTS= \
    $(_OBJ_DIR)\alpha\mountmgr.res \
    $(_OBJ_DIR)\alpha\mountmgr.obj

PASS0_ALPHA_OBJECTS=

ALPHA64_OBJECTS= \
    $(_OBJ_DIR)\alpha64\mountmgr.res \
    $(_OBJ_DIR)\alpha64\mountmgr.obj

PASS0_ALPHA64_OBJECTS=

386_OBJECTS= \
    $(_OBJ_DIR)\i386\mountmgr.res \
    $(_OBJ_DIR)\i386\mountmgr.obj

PASS0_386_OBJECTS=

IA64_OBJECTS= \
    $(_OBJ_DIR)\ia64\mountmgr.res \
    $(_OBJ_DIR)\ia64\mountmgr.obj

PASS0_IA64_OBJECTS=

