ALPHA_OBJECTS= \
    $(_OBJ_DIR)\alpha\clipdump.res \
    $(_OBJ_DIR)\alpha\clipdump.obj

PASS0_ALPHA_OBJECTS=

ALPHA64_OBJECTS= \
    $(_OBJ_DIR)\alpha64\clipdump.res \
    $(_OBJ_DIR)\alpha64\clipdump.obj

PASS0_ALPHA64_OBJECTS=

386_OBJECTS= \
    $(_OBJ_DIR)\i386\clipdump.res \
    $(_OBJ_DIR)\i386\clipdump.obj

PASS0_386_OBJECTS=

IA64_OBJECTS= \
    $(_OBJ_DIR)\ia64\clipdump.res \
    $(_OBJ_DIR)\ia64\clipdump.obj

PASS0_IA64_OBJECTS=

