ALPHA_OBJECTS= \
    $(_OBJ_DIR)\alpha\cdcache.res \
    $(_OBJ_DIR)\alpha\cdcache.obj

PASS0_ALPHA_OBJECTS=

ALPHA64_OBJECTS= \
    $(_OBJ_DIR)\alpha64\cdcache.res \
    $(_OBJ_DIR)\alpha64\cdcache.obj

PASS0_ALPHA64_OBJECTS=

386_OBJECTS= \
    $(_OBJ_DIR)\i386\cdcache.res \
    $(_OBJ_DIR)\i386\cdcache.obj

PASS0_386_OBJECTS=

IA64_OBJECTS= \
    $(_OBJ_DIR)\ia64\cdcache.res \
    $(_OBJ_DIR)\ia64\cdcache.obj

PASS0_IA64_OBJECTS=

