//-----------------------------------------------------------------------------
//
// WARNING - WARNING - WARNING - WARNING - WARNING - WARNING - WARNING - WARNING
//
// objd\i386\notifytype.h
// Generated by NFPARSE.EXE from objd\i386\notifytype.nf
// DO NOT MODIFY BY HAND
//
// WARNING - WARNING - WARNING - WARNING - WARNING - WARNING - WARNING - WARNING
//
//-----------------------------------------------------------------------------

#if defined(_NOTIFYTYPE_ENUM_)

#undef _NOTIFYTYPE_ENUM_


#elif defined(_NOTIFYTYPE_TABLE_)

#undef _NOTIFYTYPE_TABLE_


#elif defined(_NOTIFYTYPE_NAMES_)

#undef _NOTIFYTYPE_NAMES_


#elif defined(_NOTIFYTYPE_PROTO_)

#undef _NOTIFYTYPE_PROTO_


#elif defined(_NOTIFYTYPE_INLINE_)

#undef _NOTIFYTYPE_INLINE_


#endif

