ALPHA_OBJECTS= \
    $(_OBJ_DIR)\alpha\control.res \
    $(_OBJ_DIR)\alpha\init.obj

PASS0_ALPHA_OBJECTS=

ALPHA64_OBJECTS= \
    $(_OBJ_DIR)\alpha64\control.res \
    $(_OBJ_DIR)\alpha64\init.obj

PASS0_ALPHA64_OBJECTS=

386_OBJECTS= \
    $(_OBJ_DIR)\i386\control.res \
    $(_OBJ_DIR)\i386\init.obj

PASS0_386_OBJECTS=

IA64_OBJECTS= \
    $(_OBJ_DIR)\ia64\control.res \
    $(_OBJ_DIR)\ia64\init.obj

PASS0_IA64_OBJECTS=

