ALPHA_OBJECTS= \
    $(_OBJ_DIR)\alpha\setreg.res \
    $(_OBJ_DIR)\alpha\setreg.obj

PASS0_ALPHA_OBJECTS=

ALPHA64_OBJECTS= \
    $(_OBJ_DIR)\alpha64\setreg.res \
    $(_OBJ_DIR)\alpha64\setreg.obj

PASS0_ALPHA64_OBJECTS=

386_OBJECTS= \
    $(_OBJ_DIR)\i386\setreg.res \
    $(_OBJ_DIR)\i386\setreg.obj

PASS0_386_OBJECTS=

IA64_OBJECTS= \
    $(_OBJ_DIR)\ia64\setreg.res \
    $(_OBJ_DIR)\ia64\setreg.obj

PASS0_IA64_OBJECTS=

