ALPHA_OBJECTS= \
    $(_OBJ_DIR)\alpha\sysinv.res \
    $(_OBJ_DIR)\alpha\sysinv.obj

PASS0_ALPHA_OBJECTS=

ALPHA64_OBJECTS= \
    $(_OBJ_DIR)\alpha64\sysinv.res \
    $(_OBJ_DIR)\alpha64\sysinv.obj

PASS0_ALPHA64_OBJECTS=

386_OBJECTS= \
    $(_OBJ_DIR)\i386\sysinv.res \
    $(_OBJ_DIR)\i386\sysinv.obj

PASS0_386_OBJECTS=

IA64_OBJECTS= \
    $(_OBJ_DIR)\ia64\sysinv.res \
    $(_OBJ_DIR)\ia64\sysinv.obj

PASS0_IA64_OBJECTS=

