ALPHA_OBJECTS= \
    $(_OBJ_DIR)\alpha\allpage.obj \
    $(_OBJ_DIR)\alpha\commit.obj

PASS0_ALPHA_OBJECTS=

ALPHA64_OBJECTS= \
    $(_OBJ_DIR)\alpha64\allpage.obj \
    $(_OBJ_DIR)\alpha64\commit.obj

PASS0_ALPHA64_OBJECTS=

386_OBJECTS= \
    $(_OBJ_DIR)\i386\allpage.obj \
    $(_OBJ_DIR)\i386\commit.obj

PASS0_386_OBJECTS=

IA64_OBJECTS= \
    $(_OBJ_DIR)\ia64\allpage.obj \
    $(_OBJ_DIR)\ia64\commit.obj

PASS0_IA64_OBJECTS=

