ALPHA_OBJECTS= \
    $(_OBJ_DIR)\alpha\ckcnv.res \
    $(_OBJ_DIR)\alpha\ckcnv.obj

PASS0_ALPHA_OBJECTS=

ALPHA64_OBJECTS= \
    $(_OBJ_DIR)\alpha64\ckcnv.res \
    $(_OBJ_DIR)\alpha64\ckcnv.obj

PASS0_ALPHA64_OBJECTS=

386_OBJECTS= \
    $(_OBJ_DIR)\i386\ckcnv.res \
    $(_OBJ_DIR)\i386\ckcnv.obj

PASS0_386_OBJECTS=

IA64_OBJECTS= \
    $(_OBJ_DIR)\ia64\ckcnv.res \
    $(_OBJ_DIR)\ia64\ckcnv.obj

PASS0_IA64_OBJECTS=

