ALPHA_OBJECTS= \
    $(_OBJ_DIR)\alpha\patha.obj \
    $(_OBJ_DIR)\alpha\nativea.obj

PASS0_ALPHA_OBJECTS=

ALPHA64_OBJECTS= \
    $(_OBJ_DIR)\alpha64\patha.obj \
    $(_OBJ_DIR)\alpha64\nativea.obj

PASS0_ALPHA64_OBJECTS=

386_OBJECTS= \
    $(_OBJ_DIR)\i386\patha.obj \
    $(_OBJ_DIR)\i386\nativea.obj

PASS0_386_OBJECTS=

IA64_OBJECTS= \
    $(_OBJ_DIR)\ia64\patha.obj \
    $(_OBJ_DIR)\ia64\nativea.obj

PASS0_IA64_OBJECTS=

