ALPHA_OBJECTS= \
    $(_OBJ_DIR)\alpha\shlunimp.obj \
    $(_OBJ_DIR)\alpha\proxypg.obj

PASS0_ALPHA_OBJECTS=

ALPHA64_OBJECTS= \
    $(_OBJ_DIR)\alpha64\shlunimp.obj \
    $(_OBJ_DIR)\alpha64\proxypg.obj

PASS0_ALPHA64_OBJECTS=

386_OBJECTS= \
    $(_OBJ_DIR)\i386\shlunimp.obj \
    $(_OBJ_DIR)\i386\proxypg.obj

PASS0_386_OBJECTS=

IA64_OBJECTS= \
    $(_OBJ_DIR)\ia64\shlunimp.obj \
    $(_OBJ_DIR)\ia64\proxypg.obj

PASS0_IA64_OBJECTS=

