ALPHA_OBJECTS= \
    $(_OBJ_DIR)\alpha\clockres.res \
    $(_OBJ_DIR)\alpha\clock.obj

PASS0_ALPHA_OBJECTS=

ALPHA64_OBJECTS= \
    $(_OBJ_DIR)\alpha64\clockres.res \
    $(_OBJ_DIR)\alpha64\clock.obj

PASS0_ALPHA64_OBJECTS=

386_OBJECTS= \
    $(_OBJ_DIR)\i386\clockres.res \
    $(_OBJ_DIR)\i386\clock.obj

PASS0_386_OBJECTS=

IA64_OBJECTS= \
    $(_OBJ_DIR)\ia64\clockres.res \
    $(_OBJ_DIR)\ia64\clock.obj

PASS0_IA64_OBJECTS=

