ALPHA_OBJECTS= \
    $(_OBJ_DIR)\alpha\res.res \
    $(_OBJ_DIR)\alpha\winver.obj

PASS0_ALPHA_OBJECTS=

ALPHA64_OBJECTS= \
    $(_OBJ_DIR)\alpha64\res.res \
    $(_OBJ_DIR)\alpha64\winver.obj

PASS0_ALPHA64_OBJECTS=

386_OBJECTS= \
    $(_OBJ_DIR)\i386\res.res \
    $(_OBJ_DIR)\i386\winver.obj

PASS0_386_OBJECTS=

IA64_OBJECTS= \
    $(_OBJ_DIR)\ia64\res.res \
    $(_OBJ_DIR)\ia64\winver.obj

PASS0_IA64_OBJECTS=

