ALPHA_OBJECTS= \
    $(_OBJ_DIR)\alpha\lnkdump.res \
    $(_OBJ_DIR)\alpha\lnkdump.obj

PASS0_ALPHA_OBJECTS=

ALPHA64_OBJECTS= \
    $(_OBJ_DIR)\alpha64\lnkdump.res \
    $(_OBJ_DIR)\alpha64\lnkdump.obj

PASS0_ALPHA64_OBJECTS=

386_OBJECTS= \
    $(_OBJ_DIR)\i386\lnkdump.res \
    $(_OBJ_DIR)\i386\lnkdump.obj

PASS0_386_OBJECTS=

IA64_OBJECTS= \
    $(_OBJ_DIR)\ia64\lnkdump.res \
    $(_OBJ_DIR)\ia64\lnkdump.obj

PASS0_IA64_OBJECTS=

