ALPHA_OBJECTS= \
    $(_OBJ_DIR)\alpha\mshtmler.res \
    $(_OBJ_DIR)\alpha\libmain.obj

PASS0_ALPHA_OBJECTS=

ALPHA64_OBJECTS= \
    $(_OBJ_DIR)\alpha64\mshtmler.res \
    $(_OBJ_DIR)\alpha64\libmain.obj

PASS0_ALPHA64_OBJECTS=

386_OBJECTS= \
    $(_OBJ_DIR)\i386\mshtmler.res \
    $(_OBJ_DIR)\i386\libmain.obj

PASS0_386_OBJECTS=

IA64_OBJECTS= \
    $(_OBJ_DIR)\ia64\mshtmler.res \
    $(_OBJ_DIR)\ia64\libmain.obj

PASS0_IA64_OBJECTS=

