ALPHA_OBJECTS= \
    $(_OBJ_DIR)\alpha\multimed.res \
    $(_OBJ_DIR)\alpha\multimed.obj

PASS0_ALPHA_OBJECTS=

ALPHA64_OBJECTS= \
    $(_OBJ_DIR)\alpha64\multimed.res \
    $(_OBJ_DIR)\alpha64\multimed.obj

PASS0_ALPHA64_OBJECTS=

386_OBJECTS= \
    $(_OBJ_DIR)\i386\multimed.res \
    $(_OBJ_DIR)\i386\multimed.obj

PASS0_386_OBJECTS=

IA64_OBJECTS= \
    $(_OBJ_DIR)\ia64\multimed.res \
    $(_OBJ_DIR)\ia64\multimed.obj

PASS0_IA64_OBJECTS=

