ALPHA_OBJECTS= \
    $(_OBJ_DIR)\alpha\charencoder.obj \
    $(_OBJ_DIR)\alpha\encodingstream.obj

PASS0_ALPHA_OBJECTS=

ALPHA64_OBJECTS= \
    $(_OBJ_DIR)\alpha64\charencoder.obj \
    $(_OBJ_DIR)\alpha64\encodingstream.obj

PASS0_ALPHA64_OBJECTS=

386_OBJECTS= \
    $(_OBJ_DIR)\i386\charencoder.obj \
    $(_OBJ_DIR)\i386\encodingstream.obj

PASS0_386_OBJECTS=

IA64_OBJECTS= \
    $(_OBJ_DIR)\ia64\charencoder.obj \
    $(_OBJ_DIR)\ia64\encodingstream.obj

PASS0_IA64_OBJECTS=

