ALPHA_OBJECTS= \
    $(_OBJ_DIR)\alpha\dbgkport.obj \
    $(_OBJ_DIR)\alpha\dbgkproc.obj

PASS0_ALPHA_OBJECTS=

ALPHA64_OBJECTS= \
    $(_OBJ_DIR)\alpha64\dbgkport.obj \
    $(_OBJ_DIR)\alpha64\dbgkproc.obj

PASS0_ALPHA64_OBJECTS=

386_OBJECTS= \
    $(_OBJ_DIR)\i386\dbgkport.obj \
    $(_OBJ_DIR)\i386\dbgkproc.obj

PASS0_386_OBJECTS=

IA64_OBJECTS= \
    $(_OBJ_DIR)\ia64\dbgkport.obj \
    $(_OBJ_DIR)\ia64\dbgkproc.obj

PASS0_IA64_OBJECTS=

