ALPHA_OBJECTS= \
    $(_OBJ_DIR)\alpha\sublocal.res \
    $(_OBJ_DIR)\alpha\sublocal.obj

PASS0_ALPHA_OBJECTS=

ALPHA64_OBJECTS= \
    $(_OBJ_DIR)\alpha64\sublocal.res \
    $(_OBJ_DIR)\alpha64\sublocal.obj

PASS0_ALPHA64_OBJECTS=

386_OBJECTS= \
    $(_OBJ_DIR)\i386\sublocal.res \
    $(_OBJ_DIR)\i386\sublocal.obj

PASS0_386_OBJECTS=

IA64_OBJECTS= \
    $(_OBJ_DIR)\ia64\sublocal.res \
    $(_OBJ_DIR)\ia64\sublocal.obj

PASS0_IA64_OBJECTS=

