ALPHA_OBJECTS= \
    $(_OBJ_DIR)\alpha\online.res \
    $(_OBJ_DIR)\alpha\term.obj

PASS0_ALPHA_OBJECTS=

ALPHA64_OBJECTS= \
    $(_OBJ_DIR)\alpha64\online.res \
    $(_OBJ_DIR)\alpha64\term.obj

PASS0_ALPHA64_OBJECTS=

386_OBJECTS= \
    $(_OBJ_DIR)\i386\online.res \
    $(_OBJ_DIR)\i386\term.obj

PASS0_386_OBJECTS=

IA64_OBJECTS= \
    $(_OBJ_DIR)\ia64\online.res \
    $(_OBJ_DIR)\ia64\term.obj

PASS0_IA64_OBJECTS=

