ALPHA_OBJECTS= \
    $(_OBJ_DIR)\alpha\systray.res \
    $(_OBJ_DIR)\alpha\systray.obj

PASS0_ALPHA_OBJECTS=

ALPHA64_OBJECTS= \
    $(_OBJ_DIR)\alpha64\systray.res \
    $(_OBJ_DIR)\alpha64\systray.obj

PASS0_ALPHA64_OBJECTS=

386_OBJECTS= \
    $(_OBJ_DIR)\i386\systray.res \
    $(_OBJ_DIR)\i386\systray.obj

PASS0_386_OBJECTS=

IA64_OBJECTS= \
    $(_OBJ_DIR)\ia64\systray.res \
    $(_OBJ_DIR)\ia64\systray.obj

PASS0_IA64_OBJECTS=

