ALPHA_OBJECTS= \
    $(_OBJ_DIR)\alpha\internat.res \
    $(_OBJ_DIR)\alpha\internat.obj

PASS0_ALPHA_OBJECTS=

ALPHA64_OBJECTS= \
    $(_OBJ_DIR)\alpha64\internat.res \
    $(_OBJ_DIR)\alpha64\internat.obj

PASS0_ALPHA64_OBJECTS=

386_OBJECTS= \
    $(_OBJ_DIR)\i386\internat.res \
    $(_OBJ_DIR)\i386\internat.obj

PASS0_386_OBJECTS=

IA64_OBJECTS= \
    $(_OBJ_DIR)\ia64\internat.res \
    $(_OBJ_DIR)\ia64\internat.obj

PASS0_IA64_OBJECTS=

