ALPHA_OBJECTS= \
    $(_OBJ_DIR)\alpha\hshstrss.res \
    $(_OBJ_DIR)\alpha\hshstrss.obj

PASS0_ALPHA_OBJECTS=

ALPHA64_OBJECTS= \
    $(_OBJ_DIR)\alpha64\hshstrss.res \
    $(_OBJ_DIR)\alpha64\hshstrss.obj

PASS0_ALPHA64_OBJECTS=

386_OBJECTS= \
    $(_OBJ_DIR)\i386\hshstrss.res \
    $(_OBJ_DIR)\i386\hshstrss.obj

PASS0_386_OBJECTS=

IA64_OBJECTS= \
    $(_OBJ_DIR)\ia64\hshstrss.res \
    $(_OBJ_DIR)\ia64\hshstrss.obj

PASS0_IA64_OBJECTS=

