ALPHA_OBJECTS= \
    $(_OBJ_DIR)\alpha\urlostrm.obj \
    $(_OBJ_DIR)\alpha\hlinkez.obj

PASS0_ALPHA_OBJECTS=

ALPHA64_OBJECTS= \
    $(_OBJ_DIR)\alpha64\urlostrm.obj \
    $(_OBJ_DIR)\alpha64\hlinkez.obj

PASS0_ALPHA64_OBJECTS=

386_OBJECTS= \
    $(_OBJ_DIR)\i386\urlostrm.obj \
    $(_OBJ_DIR)\i386\hlinkez.obj

PASS0_386_OBJECTS=

IA64_OBJECTS= \
    $(_OBJ_DIR)\ia64\urlostrm.obj \
    $(_OBJ_DIR)\ia64\hlinkez.obj

PASS0_IA64_OBJECTS=

