ALPHA_OBJECTS= \
    $(_OBJ_DIR)\alpha\eventcmd.res \
    $(_OBJ_DIR)\alpha\eventcmd.obj \
    $(_OBJ_DIR)\alpha\errors.obj \
    $(_OBJ_DIR)\alpha\operation.obj \
    $(_OBJ_DIR)\alpha\parser.obj \
    $(_OBJ_DIR)\alpha\registry.obj \
    $(_OBJ_DIR)\alpha\snmpctrl.obj

PASS0_ALPHA_OBJECTS=

ALPHA64_OBJECTS= \
    $(_OBJ_DIR)\alpha64\eventcmd.res \
    $(_OBJ_DIR)\alpha64\eventcmd.obj \
    $(_OBJ_DIR)\alpha64\errors.obj \
    $(_OBJ_DIR)\alpha64\operation.obj \
    $(_OBJ_DIR)\alpha64\parser.obj \
    $(_OBJ_DIR)\alpha64\registry.obj \
    $(_OBJ_DIR)\alpha64\snmpctrl.obj

PASS0_ALPHA64_OBJECTS=

386_OBJECTS= \
    $(_OBJ_DIR)\i386\eventcmd.res \
    $(_OBJ_DIR)\i386\eventcmd.obj \
    $(_OBJ_DIR)\i386\errors.obj \
    $(_OBJ_DIR)\i386\operation.obj \
    $(_OBJ_DIR)\i386\parser.obj \
    $(_OBJ_DIR)\i386\registry.obj \
    $(_OBJ_DIR)\i386\snmpctrl.obj

PASS0_386_OBJECTS=

IA64_OBJECTS= \
    $(_OBJ_DIR)\ia64\eventcmd.res \
    $(_OBJ_DIR)\ia64\eventcmd.obj \
    $(_OBJ_DIR)\ia64\errors.obj \
    $(_OBJ_DIR)\ia64\operation.obj \
    $(_OBJ_DIR)\ia64\parser.obj \
    $(_OBJ_DIR)\ia64\registry.obj \
    $(_OBJ_DIR)\ia64\snmpctrl.obj

PASS0_IA64_OBJECTS=

